### ISSUE TITLE
abbyy XML parsing is failing in integration tests

### ISSUE THREAD

**Issue by edsu** [sul-dlss/common-accessioning#1336] opened 2024-08-29 20:18 UTC
I noticed that the [preassembly_ocr_document_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_ocr_document_spec.rb) integration test passes, but also routinely generates this HoneyBadger error?

https://app.honeybadger.io/projects/52894/faults/109727764/01J683JJTTHAVPB6NHPW0FMM68

From the stack trace it seems that this is happening in the [cleanup_abbyy_results](https://github.com/sul-dlss/common-accessioning/blob/main/lib/dor/text_extraction/ocr.rb#L108) step, and that maybe it is failing because it is happening after [cleanup_output_folder](https://github.com/sul-dlss/common-accessioning/blob/c0c95b8878ac913be638dc7a5ccbcda7c08ceb8a/lib/dor/text_extraction/ocr.rb#L33) which removes the same directory?

**Comment by peetucket** [comment] 2024-08-29 21:03
From Slack: (https://stanfordlib.slack.com/archives/C06EVDJV45N/p1724965341756019)

It also looks like that exception stacktrace shows it is occurring in a different part (not in cleanup)

appears to be having trouble parsing the result XML that is coming back from abbyy as part of the stage-files step earlier, but this doesn't seem to make a difference for successfully completing the workflow and letting the integration test pass

still worth keeping on the prod priorities board to check into why the integration test data is producing unparseable abbyy XML in case it is something that may occur with production data later

**Comment by peetucket** [comment] 2024-09-05 20:46
Closed by #1338 

There wasn't actually a problem - the issue is that PDFs do not generate Alto XML but our code was not properly detecting this and thus generating an HB alert.  This should no longer happen by improving the check.

**Closed by peetucket** 2024-09-05 20:46 UTC
Labels: bug
