### ISSUE TITLE
Run SdrIngestTransfer on dor-services-app.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#168] opened 2019-01-25 21:46 UTC
Currently we do
` Dor::SdrIngestService.transfer(obj)`, which is making the deprecation:

```
DEPRECATION WARNING: you are using dor-services to invoke calls to dor-services-app.  Use dor-services-client instead. (called from get_signature_catalog at /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.14/lib/dor/utils/sdr_client.rb:35)
```

**Comment by mjgiarlo** [comment] 2019-11-19 18:02
Closing as older duplicate of #437

**Closed by mjgiarlo** 2019-11-19 18:02 UTC
Labels: tech debt
